export const HEROICONS = {
  CIRCLE_STACK_20_SOLID: 'i-heroicons-circle-stack-20-solid',
  INFORMATION_CIRCLE: 'i-heroicons-information-circle',
  MOON_20_SOLID: 'i-heroicons-moon-20-solid',
  SUN_20_SOLID: 'i-heroicons-sun-20-solid',
  BARS_3: 'i-heroicons-bars-3',
  HOME: 'i-heroicons-home',
  FOLDER: 'i-heroicons-folder',
  CHART_BAR: 'i-heroicons-chart-bar',
  COG: 'i-heroicons-cog',
  ARROW_LEFT: 'i-heroicons-arrow-left',
  ARROW_RIGHT: 'i-heroicons-arrow-right',
  ARROW_PATH: 'i-heroicons-arrow-path',
  ARROW_RIGHT_START_ON_RECTANGLE: 'i-heroicons-arrow-right-start-on-rectangle',
  CLIPBOARD_DOCUMENT_SOLID: 'i-heroicons-clipboard-document-solid',
  CHECK: 'i-heroicons-check',
  CHEVRON_DOWN_20_SOLID: 'i-heroicons-chevron-down-20-solid',
  QUESTION_MARK_CIRCLE: 'i-heroicons-question-mark-circle',
  X_MARK: 'i-heroicons-x-mark'
}
