name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Docker tag
        id: tag
        run: |
          if [[ "${{ github.head_ref }}" == "master" ]]; then
            echo "tag=latest" >> $GITHUB_ENV
          elif [[ "${{ github.head_ref }}" == "dev" ]]; then
            echo "tag=unstable" >> $GITHUB_ENV
          else
            echo "Unexpected branch: ${{ github.head_ref }}"
            exit 1
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/yandex-tracker-dashboard:${{ env.tag }}
